### ISSUE TITLE
增强

### ISSUE THREAD

**Issue by al-wei** [Giant-Salted-Fish/Key-Binding-Patch#11]
https://www.curseforge.com/minecraft/mc-mods/rebind

近日找到一个mod，功能非常强的按键控制。

1、隐藏，即不显示于控制中。
2、自定义，按键绑定，比如在配置中设置按键值（或许可以固定，也就是不能在游戏中更改，但是没试过）
3、禁用，即无法触发，比如按下攻击无法攻击。
（原理可能是将其自定义为：空，也就是esc清除绑定，即键值：0；不太可能做到完全删除）

（设置，值0，设置隐藏，便可达到去除按键的效果）

但是可惜的是为1.12.2版本，并且停更。有没有兴趣加入功能呢！

**Comment by Giant-Salted-Fish** [comment]
听起来像是给整合包用的功能？隐藏、禁用、无法修改之类的似乎不是单人游戏中会用到功能。

**Comment by al-wei** [comment]
可以这么说，对像夏洛的地图这种模组，或者大型整合包相当实用，但是普通玩家也想要，比如去除多余按键，可以优化视觉效果，更方便查看，修改需要按键等，我就是。

目前我没看到过几个类似模组，看到过一个还有严重bug，还停更。虽然这个链接模组也停更了，但是这个运作的非常好，但是没遇到过什么bug，崩溃。

如果您能实现，也能给咱们这个模组带来更多热度。（没什么人愿意做这种模组，有的话那就有很多这种模组啦）
当然您只需要实现，隐藏，禁用，固定按键（玩家一般主要奔着隐藏禁用，固定按键都可以不做，毕竟可以游戏内改，还更有自由性，防止整合包作者固定按键），功能即可，其wiki里写的自定义按键名称等等完全没必要，而且还很麻烦。玩家想要的一般都是禁用，隐藏功能。

**Comment by al-wei** [comment]
普通玩家自己玩也会接触，如夏洛地图模组等等，无法在配置中关闭键的模组，还是很实用的。并且一般关闭还不一定能准确到某一个按键，可能是模块式，关闭整个组键。

**Comment by Giant-Salted-Fish** [comment]
为了美观隐藏用不上的按键我可以理解，禁用的话直接清空绑定按键就可以了吧？这个还有必要做成单独的功能吗？

**Comment by al-wei** [comment]
> 为了美观隐藏用不上的按键我可以理解，禁用的话直接清空绑定按键就可以了吧？这个还有必要做成单独的功能吗？

主要就是隐藏功能啊，上方禁用清空是基本。如果不禁用再隐藏，会误触。
所以有必要制作清空和隐藏，才能达到最终目的。

而如和实用和适用群体上方也说了，都适用个人，整合包。
隐藏美观是其一，其二为可以忽略一长排无用按键，更快查阅翻找更改。按键搜索可以但想想一长排简化后就不需要搜索了，可以快速短时间翻至按键。

这种按键功能肯定还是受欢迎的。

**Comment by Giant-Salted-Fish** [comment]
隐藏后肯定要自动屏蔽输入的。不过类似的功能不太适合直接整合到 KBP 里面，可以单出一个模组做这个功能，看我后面有没有时间吧。

**Comment by al-wei** [comment]
嗯这个确实背离KBP，更加合适独立。
那么打扰了。
感谢您的KBP模组。

**Comment by al-wei** [comment]
> 隐藏后肯定要自动屏蔽输入的。不过类似的功能不太适合直接整合到 KBP 里面，可以单出一个模组做这个功能，看我后面有没有时间吧。

我有个问题KBP模组支持Default Options这种模组吗（我暂时没有使用KBP）？

**Comment by Giant-Salted-Fish** [comment]
新开发了一个独立模组 [Hide Key Binding](https://github.com/Giant-Salted-Fish/Hide-Key-Binding) 做了隐藏按键绑定的功能，不依赖 KBP 使用。

**Comment by al-wei** [comment]
无需多言的爱

**Comment by Giant-Salted-Fish** [comment]
MC 百科和 Modrinth 上还在等审核，你可以先拿[这个](https://github.com/Giant-Salted-Fish/Hide-Key-Binding/releases/tag/v1.12.2-1.0.0.0)用着试试。

**Comment by al-wei** [comment]
哦，谢谢。
