### ISSUE TITLE
支持

### ISSUE THREAD

**Issue by al-wei** [Giant-Salted-Fish/Key-Binding-Patch#12]
DefaultOptions类型模组对其没有效果。
可以支持DefaultOptions类型模组吗？
或者将其添加到KBP。

**Comment by Giant-Salted-Fish** [comment]
KBP 应该不会直接集成该功能，但你可以给出你测试使用的游戏版本和模组链接，我会尽量尝试兼容类似的功能。

**Comment by al-wei** [comment]
> KBP 应该不会直接集成该功能，但你可以给出你测试使用的游戏版本和模组链接，我会尽量尝试兼容类似的功能。

DefaultOptions_1.12.2-9.2.8.jar
[MC-1.12.2] Key Binding Patch v1.3.3.0 - 2024-11-17

**Comment by al-wei** [comment]
> KBP 应该不会直接集成该功能，但你可以给出你测试使用的游戏版本和模组链接，我会尽量尝试兼容类似的功能。

大概就是这样无效的DefaultOptions
![image](https://github.com/user-attachments/assets/abe4ae22-c2d9-46d1-8383-751159b248a8)

![image](https://github.com/user-attachments/assets/a3c041cb-bbec-44d2-a990-f9b93d42ca4e)

**Comment by Giant-Salted-Fish** [comment]
好的 我这边先测试下看看问题在哪。

**Comment by al-wei** [comment]
> 好的 我这边先测试下看看问题在哪。

格式不一样

**Comment by al-wei** [comment]
格式不一样，导致根本没有储存组合键。
![image](https://github.com/user-attachments/assets/5fb8ce7c-deae-422f-8789-e0c4c9adfbca)
![image](https://github.com/user-attachments/assets/af193737-1fdd-4b3b-9160-acf81e957d9f)

**Comment by al-wei** [comment]
> 格式不一样，导致根本没有储存组合键。 ![image](https://private-user-images.githubusercontent.com/145486869/387273891-5fb8ce7c-deae-422f-8789-e0c4c9adfbca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NDI3NzIsIm5iZiI6MTczMTk0MjQ3MiwicGF0aCI6Ii8xNDU0ODY4NjkvMzg3MjczODkxLTVmYjhjZTdjLWRlYWUtNDIyZi04Nzg5LWUwYzRjOWFkZmJjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQxNTA3NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTI3NTRmMjk1MmQ4YTQyZGUxYzU1Y2U5OTQyNzNhNjJiMzk3NTdlYmYxYjc0ZTcwMjlhN2UxNGI5NTA5YmYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IhfFois2r8tzDfJ8HdROP8oxHMz4mEEPJY7fuCkLi5Y) ![image](https://private-user-images.githubusercontent.com/145486869/387273978-af193737-1fdd-4b3b-9160-acf81e957d9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NDI3NzIsIm5iZiI6MTczMTk0MjQ3MiwicGF0aCI6Ii8xNDU0ODY4NjkvMzg3MjczOTc4LWFmMTkzNzM3LTFmZGQtNGIzYi05MTYwLWFjZjgxZTk1N2Q5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQxNTA3NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzAzOGUyMmQ0YmQ5N2U0OTI4MzhkZDg4YmMyOGMxMzU4MWMxZjY5NzBlMDA4ZGYyZGU0MTBkNmEyMjA0MTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cIJR20280BYMV4NB5sxcUIdsuquWVmAM7i9GAt1RSYU)

或许它没有办法识别其它模组更改后的内容，导致所有的配置DefaultOptions都没有存。

**Comment by Giant-Salted-Fish** [comment]
那样的话可以到 Default Options 的 Github 仓库提个 issue。

**Comment by al-wei** [comment]
哦，DefaultOptions_1.12.2-9.2.8.jar 最后更新是2018年。

**Comment by Giant-Salted-Fish** [comment]
Default Options 的仓库是活跃的，最后更新在上个月，不过 1.12.2 版本未必会获得更新支持。

**Comment by al-wei** [comment]
我会先去测试

默认设置DefaultSettings是活跃的
https://www.mcmod.cn/class/4783.html

新出一个Saro´s Default Options
https://www.curseforge.com/minecraft/mc-mods/saro-s-default-options

**Comment by al-wei** [comment]
无效，只能Default Options类型、KBP二选一了

**Comment by Giant-Salted-Fish** [comment]
更改默认按键配置的功能做到 [Default Key Setup](https://github.com/Giant-Salted-Fish/Default-Key-Setup) 里了，依旧是可以不依赖 KBP 使用，你可以在项目过审前先在[这里](https://github.com/Giant-Salted-Fish/Default-Key-Setup/releases/tag/v1.12.2-1.0.0.0)获取初始版本使用。

**Comment by al-wei** [comment]
> 更改默认按键配置的功能做到 [Default Key Setup](https://github.com/Giant-Salted-Fish/Default-Key-Setup) 里了，依旧是可以不依赖 KBP 使用，你可以在项目过审前先在[这里](https://github.com/Giant-Salted-Fish/Default-Key-Setup/releases/tag/v1.12.2-1.0.0.0)获取初始版本使用。

等会这个模组可以保存，视频设置，辅助设置，高清修复等设置吗？
要混搭其它模组使用，有与DefaultOptions等有兼容吗？还是怎么操作呢？

**Comment by Giant-Salted-Fish** [comment]
DKS 只会保存按键绑定预设，不会保存其它游戏设置。至于和 DefaultOptions 之类的兼容问题，我还没有尝试过，所以不清楚。如果你遇到了类似问题，可以在 DKS 的仓库那边提 Iusse。

**Comment by al-wei** [comment]
DKS和HBK怎么使用啊？命令还是什么。

**Comment by Giant-Salted-Fish** [comment]
> DKS和HBK怎么使用啊？命令还是什么。

在游戏的模组列表里找到 DKS 和 HBK 点 config 按钮就行

**Comment by al-wei** [comment]
> > DKS和HBK怎么使用啊？命令还是什么。
> 
> 在游戏的模组列表里找到 DKS 和 HBK 点 config 按钮就行

麻烦了麻烦了，平时 DefaultOptions 命令用习惯了，忘记了config。哈哈。
在 1.12.2 我会测试三个模组，有问题我会提出。再见。
