### ISSUE TITLE
Crash with spyglass_improvements-1.5+mc1.20+forge - Immediately crashes before reaching the title screen.

### ISSUE THREAD

**Issue by ChrisLensFlare1963** [Giant-Salted-Fish/Key-Binding-Patch#14]
Minecraft + Forge version: 1.20.1-forge-47.3.12
Mod version: 1.3.3.3 (1.20.1) (also tested with 1.3.3.2, same issue)

Crash message in Minecraft launcher: 
> The game crashed whilst initializing game
> Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

Crash report + Log:
[crash-2024-12-04_22.07.05-client.txt](https://github.com/user-attachments/files/18017175/crash-2024-12-04_22.07.05-client.txt)
[latest.log](https://github.com/user-attachments/files/18017178/latest.log)

**Comment by Giant-Salted-Fish** [comment]
Fixed in KBP v1.3.3.4
