### ISSUE TITLE
Incompatible with mods that extend KeyMapping. 

### ISSUE THREAD

**Issue by mysticdrew** [Giant-Salted-Fish/Key-Binding-Patch#4]
This is primarily related to JourneyMap. 
Your call to getKey in the constructor is breaking our KeyMapping logic due to our instance variables getting set in our constructor.

https://github.com/Giant-Salted-Fish/Key-Binding-Patch/blob/b029e8777d886ef701b6df6849b8c28623b0d1f3/src/main/java/com/kbp/client/mixin/KeyBindingMixin.java#L415

We set some variables in our constructor, those are checked on the getKey call, but those variables are not set when you call getKey which then throws an NPE during modloading. I can fix this on my end for our use case with a null check, but you should probably look at another approach so that you are not breaking other mods. 

initial report:
https://github.com/TeamJM/journeymap/issues/688

**Comment by Giant-Salted-Fish** [comment]
First of all, thank for your investigation on this iusse!

I sort of assuming `KeyMapping#setKey(Input)` to be a simple function and calling it in `Mixin#setKeyAndCmbKeys(...)` to make sure others who override `setKey` method can still receive the new bound key when bound key is changed. I used `setKeyAndCmbKeys` in constructor mainly for convenience, but you are right here, `setKey` may not be fully prepared before the constructor is finished, and calling it with exactly the same bound key in construct is also pointless. I will change the mixin implementation to only setup `KeyMappingMixin#current_cmb_keys` field in constructor and avoid the invocation of `setKey` in constructor. That should solve the problem.

**Comment by Giant-Salted-Fish** [comment]
Also please verify if calling `KeyMapping#setKey(Input)` in `KeyMapping#setKeyModifierAndCode(KeyModifier, Input)` is safe for your implementation. Thanks for your report!

https://github.com/Giant-Salted-Fish/Key-Binding-Patch/blob/b029e8777d886ef701b6df6849b8c28623b0d1f3/src/main/java/com/kbp/client/mixin/KeyBindingMixin.java#L357

**Comment by mysticdrew** [comment]
That should be fine as long as it is not getting called in the constructor.

**Comment by Giant-Salted-Fish** [comment]
OK, thanks for your verification.

**Comment by mysticdrew** [comment]
Thanks!
