### ISSUE TITLE
Bugs used in conjunction with EnchantmentDescription

### ISSUE THREAD

**Issue by 10086H** [Giant-Salted-Fish/Key-Binding-Patch#6]
Bug

Mod Version

[MC-1.16.5] Key Binding Patch v1.2.0.4 - 2024-4-6.jar

EnchantmentDescriptions-1.16.5-7.1.25.jar

MC Version

1.16.5+forge36.2.42
![Screenshot_2024-04-15-20-27-07-558_net kdt pojavlaunch zh-edit](https://github.com/Giant-Salted-Fish/Key-Binding-Patch/assets/119060402/2d6f2f8d-f327-4a85-9f05-69462e37bdbc)

**Comment by Giant-Salted-Fish** [comment]
It is not caused by Key Binding Patch. I have submitted this issue to EnchantmentDescription mod. Tracker is here: https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/issues/235.

**Comment by Giant-Salted-Fish** [comment]
They have fixed this issue, please update to [7.1.27](https://legacy.curseforge.com/minecraft/mc-mods/enchantment-descriptions/files/5266527) version.
