### ISSUE TITLE
Conflict with Immersive Aircraft!

### ISSUE THREAD

**Issue by bulefire-fox** [Giant-Salted-Fish/Key-Binding-Patch#7]
### Description
When using **Immersive Aircraft** (hereafter referred to as IA) ([Luke100000/ImmersiveAircraft](https://github.com/Luke100000/ImmersiveAircraft)) in conjunction with **Key Binding Patch** (abbreviated as KBP), an issue arises where key bindings set by IA are reset to `Not Bound`. Even after reassigning these keys, they revert back to `Not Bound`, thereby preventing control of the aircraft.

<img width="578" alt="cfad10ee1efc0ed5864ba16bc33dbeb7" src="https://github.com/Giant-Salted-Fish/Key-Binding-Patch/assets/142371489/51627e06-bfef-4b4f-a45a-04907d59cd2d">

### Affected Versions
- **Immersive Aircraft**: 0.7.5
- **Key Binding Patch**: 1.3.1.0
- **Minecraft**: 1.20.1
- **Forge**: 47

### Steps to Reproduce
1. Install Minecraft version 1.20.1 with Forge 47.
2. Add Immersive Aircraft version 0.7.5 and Key Binding Patch version 1.3.1.0 to the mods folder.
3. Launch the game and navigate to IA's key bindings.
4. Observe that some or all IA-related key bindings are listed as `Not Bound`.
5. Attempt to rebind the keys; notice they revert to `Not Bound` upon restarting the game or sometimes even immediately.

### Expected Behavior
Key bindings set within Immersive Aircraft should persist across game sessions and not be altered by the presence of Key Binding Patch.

### Actual Behavior
Key bindings are incorrectly reset to `Not Bound`, rendering aircraft controls unusable.

### Additional Information
If any additional logs, screenshots, or details are needed to diagnose the problem, please let me know. I'm eager to help resolve this compatibility issue to continue enjoying both mods together.

# warn!: The above text was translated by 通义千问(Qwen), which may contain ambiguity.
# 警告！：以上文本由通义千问翻译，可能存再歧义

**Comment by Giant-Salted-Fish** [comment]
Can not reproduce this problem with {Forge 47, Immersive Aircraft 1.0.0, Key Binding Patch 1.3.1.0} configuration. Please verify if the problem still exists on your side.

使用 Forge 47，Immersive Aircraft 1.0.0，按键绑定补丁 1.3.1.0 进行本地测试无法复现上述问题，请检查描述的问题是否依然存在。

**Comment by bulefire-fox** [comment]
在最新版(Immersive Aircraft 1.0.0，按键绑定补丁 1.3.1.0 forge47)中无上述问题。

**Comment by Giant-Salted-Fish** [comment]
好的，谢谢你的反馈。
